// Generated by CoffeeScript 1.10.0
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: ['./bower_components/angular/angular.js', 'bower_components/angular/angular.js', 'bower_components/angular-animate/angular-animate.js', 'bower_components/angular-aria/angular-aria.js', 'bower_components/angular-cookies/angular-cookies.js', 'bower_components/angular-resource/angular-resource.js', 'bower_components/angular-route/angular-route.js', 'bower_components/angular-sanitize/angular-sanitize.js', 'bower_components/angular-mocks/angular-mocks.js', './{app,components}/**/*.js', './test/**/*.js', './app/views/**/*.html'],
    preprocessors: {
      '**/*.html': 'ng-html2js'
    },
    ngHtml2JsPreprocessor: {
      stripPrefix: 'app/'
    },
    exclude: [],
    port: 8080,
    logLevel: config.LOG_INFO,
    reporters: ['spec'],
    autoWatch: false,
    browsers: ['PhantomJS'],
    singleRun: false
  });
};
