// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name progressArcApp.controller:AboutCtrl
  * @description
  * # AboutCtrl
  * Controller of the progressArcApp
 */
var AboutCtrl;

AboutCtrl = function() {
  var vm;
  vm = this;
  vm.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
};

AboutCtrl.$inject = [];

angular.module('progressArcApp').controller('AboutCtrl', AboutCtrl);
