// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name progressArcApp.controller:MyTestCtrl
  * @description
  * # MyTestCtrl
  * Controller of the progressArcApp
 */
var MyTestCtrl;

MyTestCtrl = function() {
  var vm;
  vm = this;
  vm.description = 'Back in business';
};

MyTestCtrl.$inject = [];

angular.module('progressArcApp').controller('MyTestCtrl', MyTestCtrl);
