// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc function
  * @name progressArcApp.controller:ProgressArcCtrl
  * @description
  * # ProgressArcCtrl
  * Controller of the progressArcApp
 */
var ProgressArcCtrl;

ProgressArcCtrl = function() {
  var vm;
  vm = this;
  vm.title = 'Progress';
  vm.actual_display = vm.actual + '%';
  vm.chartData = [20, 30, 40, 50];
};

angular.module('progressArcApp').controller('ProgressArcCtrl', ProgressArcCtrl);
