// Generated by CoffeeScript 1.10.0
'use strict';
describe('Directive: myTestDirective', function() {
  var element, scope;
  beforeEach(module('progressArcApp'));
  beforeEach(module('views/templates/mytestdirective.html'));
  scope = {};
  element = {};
  beforeEach(inject(function($rootScope, $compile) {
    scope = $rootScope.$new();
    element = angular.element('<my-test-directive></my-test-directive>');
    element = $compile(element)(scope);
    return scope.$digest();
  }));
  it('should display the entire description', inject(function() {
    return expect(element.text()).toBe('Description: Back in business');
  }));
});
