// Generated by CoffeeScript 1.10.0
'use strict';
describe('Controller: MyTestCtrl', function() {
  var scope, vm;
  beforeEach(module('progressArcApp'));
  vm = {};
  scope = {};
  beforeEach(inject(function($controller, $rootScope) {
    scope = $rootScope.$new();
    return vm = $controller('MyTestCtrl', {});
  }));
  return it('should provide a default description', function() {
    return expect(vm.description).toBe('Back in business');
  });
});
