// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc service
  * @name progressArcApp.Conversion
  * @description
  * # Conversion
  * Factory in the progressArcApp.
 */
var Conversion;

Conversion = function() {
  var floatToPercent, floatToRadians;
  floatToRadians = function(percent) {
    return percent * 360 * Math.PI / 180;
  };
  floatToPercent = function(float) {
    return float * 100;
  };
  return {
    floatToRadians: floatToRadians,
    floatToPercent: floatToPercent
  };
};

angular.module('progressArcApp').factory('Conversion', Conversion);
