// Generated by CoffeeScript 1.10.0
'use strict';

/**
  * @ngdoc directive
  * @name progressArcApp.directive:myTestDirective
  * @description
  * # myTestDirective
 */
var myTestDirective;

myTestDirective = function() {
  return {
    restrict: 'E',
    templateUrl: 'views/templates/mytestdirective.html',
    bindToController: true,
    controller: 'MyTestCtrl',
    controllerAs: 'vm'
  };
};

myTestDirective.$inject = [];

angular.module('progressArcApp').directive('myTestDirective', myTestDirective);
